//
// Sorting Types
//
type BUBBLE_SORT = "BUBBLE SORT";
type SELECTION_SORT = "SELECTION SORT";
type INSERTION_SORT = "INSERTION SORT";
type MERGE_SORT = "MERGE SORT";
type QUICK_SORT = "QUICK SORT";
type RANDOM_QUICK_SORT = "RANDOM QUICK SORT";
type COUNTING_SORT = "COUNTING SORT";
type RADIX_SORT = "RADIX SORT";

//
//
//
type SORTING_METHOD =
  | BUBBLE_SORT
  | SELECTION_SORT
  | INSERTION_SORT
  | MERGE_SORT
  | QUICK_SORT
  | RANDOM_QUICK_SORT
  | COUNTING_SORT
  | RADIX_SORT;

type DATA_SET = { value: number; id: string }[];
type SORTING_STEPS = DATA_SET[];
