//
// Sorting Types
//
type BUBBLE_SORT = "BUBBLE SORT";
type SELECTION_SORT = "SELECTION SORT";
type INSERTION_SORT = "INSERTION SORT";
type QUICK_SORT = "QUICK SORT";
type RANDOM_QUICK_SORT = "RANDOM QUICK SORT";
type COCKTAIL_SORT = "COCKTAIL SORT";

//
//
//
type SORTING_METHOD =
  | BUBBLE_SORT
  | SELECTION_SORT
  | INSERTION_SORT
  | QUICK_SORT
  | RANDOM_QUICK_SORT
  | COCKTAIL_SORT;

type DATA_POINT = {
  value: number;
  id: string;
  active: boolean;
  done: boolean;
};
type DATA_SET = DATA_POINT[];
type SORTING_STEPS = DATA_SET[];
